### PR TITLE
Feature mark as used

### LINKED ISSUE #29: Mark addresses as used
A user should be able to mark an addresss as used, so they're reminded to not use it again. Maybe with a swipe gesture, confirmed with "mark as used?", similar to how delete works in a tableview.

We should not hide the address. A light strike-through is probably good enough.

### PR DESCRIPTION
**Pull request by w-i-n-s**
Resolve #29

### CODE REVIEW

**Comment by Sjors** [comment]
Can you change the text here to "Mark used"? Ideally also change the color to something non-dangerous.
Schermafbeelding 2021-06-14 om 13 13 47

The strike-through looks fine, thanks:
Schermafbeelding 2021-06-14 om 13 15 19

When the user does another swipe on it, maybe call it "Mark unused" and undo the action.


As for updating the UI, can't you redraw the cell after `markAsUsed(indexSet: IndexSet)` in `AddressesViewModel.swift`?

**Comment by w-i-n-s** [comment]
> (needs rebase)

sure

> Can you change the text here to "Mark used"? Ideally also change the color to something non-dangerous.

For the moment it doesn't have a straightway to solve it.  Of course, I can bring `UIKIt`'s controller here to make text and color as we need. But I recommend not to invest time here. UI side can wait before iOS15, I hope. (details)[https://github.com/Sjors/nthkey-ios/issues/29#issuecomment-860251724]

> When the user does another swipe on it, maybe call it "Mark unused" (or "Undo") and undo the action.

Yes, we can toggle it.

> As for updating the UI, can't you redraw the cell after `markAsUsed(indexSet: IndexSet)` in `AddressesViewModel.swift`?

No, it doesn't work like this. The SwiftUI 'List' observes the array and if the array will change - then the list will redraw. View of every row also observe changes in the `AddressEntity` item. But the item is the object - it means `objectWillChange` will not send when we mark the address as used. I'll try to map the CoreData object into a structure (which looks weird I think) - because a change in structure should send the `objectWillChange` signal.

**Comment by Sjors** [comment]
Ok, waiting for iOs 15 is fine for improving the text and color. And otherwise we could add a checkbox instead, rather than the swipe gesture.

**Comment by w-i-n-s** [comment]
> add a checkbox instead, rather than the swipe gesture.

fixed in 647d0d8668743507208a93e68c9946398ac263b1

**Pull request merged**
