### PR TITLE
Fix wrong layout issue

### PR DESCRIPTION
**Pull request by w-i-n-s**
Fix issue #13

### CODE REVIEW

**Comment by Sjors** [comment]
That works, thanks!

Can you rebase and change the commit message to something a bit more informative? E.g.

```
Fix address screen layout constraint

Fixes #13
```


I still get a bunch of noise in the console, but that's a seperate issue probably:
```
2021-03-07 17:05:35.283735+0100 NthKey[7417:17891608] screen parameters are unexpected: MGScreenClass1125x2436x3x495 SCREEN_TYPE(1125,2436,3,495)
2021-03-07 17:05:35.309439+0100 NthKey[7417:17891608] Metal API Validation Enabled
2021-03-07 17:05:35.455422+0100 NthKey[7417:17891608] The filter 'CIPortraitEffectSpillCorrection' is not implemented in the bundle at /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/CoreImage/PortraitFilters.cifilter.
2021-03-07 17:05:35.484019+0100 NthKey[7417:17891608] screen parameters are unexpected: MGScreenClass1125x2436x3x495 SCREEN_TYPE(1125,2436,3,495)
2021-03-07 17:05:35.484207+0100 NthKey[7417:17891608] screen parameters are unexpected: MGScreenClass1125x2436x3x495 SCREEN_TYPE(1125,2436,3,495)
2021-03-07 17:05:35.484363+0100 NthKey[7417:17891608] screen parameters are unexpected: MGScreenClass1125x2436x3x495 SCREEN_TYPE(1125,2436,3,495)
2021-03-07 17:05:35.484517+0100 NthKey[7417:17891608] screen parameters are unexpected: MGScreenClass1125x2436x3x495 SCREEN_TYPE(1125,2436,3,495)
2021-03-07 17:05:35.484655+0100 NthKey[7417:17891608] screen parameters are unexpected: MGScreenClass1125x2436x3x495 SCREEN_TYPE(1125,2436,3,495)
2021-03-07 17:05:35.484929+0100 NthKey[7417:17891608] screen parameters are unexpected: MGScreenClass1125x2436x3x495 SCREEN_TYPE(1125,2436,3,495)
2021-03-07 17:05:35.621031+0100 NthKey[7417:17891608] screen parameters are unexpected: MGScreenClass1125x2436x3x495 SCREEN_TYPE(1125,2436,3,495)
```

**Comment by w-i-n-s** [comment]
> That works, thanks!
> 
> Can you rebase and change the commit message to something a bit more informative? E.g.
> 
> ```
> Fix address screen layout constraint
> 
> Fixes #13
> ```

sure, fixed in 6f592f340ac2a691c1250d3dcbe414a9eab7d2e7

**Comment by w-i-n-s** [comment]
@Sjors 
> I still get a bunch of noise in the console, but that's a seperate issue probably:

separated into new issue #18

**Comment by Sjors** [comment]
Thanks!

**Pull request merged**
